baseURL = "/"
languageCode = "en-us"
title = "Hyperchesbot's Ramblings"
theme = "swiftcode"

[params]
	[params.designer]
	    name = "hyperchessbot"
	    url = "https://github.com/hyperchessbot"

[menu]
	[[menu.main]]
		name = "About"
		url = "about"
		weight = 1
